'use client';

import { Box, Container, Typography, Link as MuiLink, Divider } from '@mui/material';
import { Scale, AlertTriangle } from 'lucide-react';
import Link from 'next/link';

export default function Footer() {
  return (
    <Box
      component="footer"
      sx={{
        mt: 'auto',
        borderTop: '1px solid',
        borderColor: 'divider',
        bgcolor: 'background.paper',
        py: 4,
        px: 2,
      }}
    >
      <Container maxWidth="lg">
        {/* Legal Disclaimer */}
        <Box
          sx={{
            display: 'flex',
            alignItems: 'flex-start',
            gap: 1.5,
            p: 2.5,
            borderRadius: 2,
            bgcolor: 'rgba(245,158,11,0.05)',
            border: '1px solid',
            borderColor: 'rgba(245,158,11,0.2)',
            mb: 3,
          }}
        >
          <AlertTriangle size={18} color="#f59e0b" style={{ flexShrink: 0, marginTop: 1 }} />
          <Typography variant="caption" color="text.secondary" lineHeight={1.7}>
            <strong style={{ color: 'inherit' }}>Legal Disclaimer:</strong> Documents generated by My Legal Notice are
            AI-drafted templates for informational purposes only and do NOT constitute legal advice. The content may
            contain errors or may not be applicable to your specific situation. Always consult a qualified and licensed
            advocate before sending any legal notice or initiating legal proceedings. My Legal Notice is not a law firm
            and is not engaged in the practice of law.
          </Typography>
        </Box>

        <Divider sx={{ my: 2.5 }} />

        <Box
          sx={{
            display: 'flex',
            flexDirection: { xs: 'column', sm: 'row' },
            justifyContent: 'space-between',
            alignItems: { xs: 'flex-start', sm: 'center' },
            gap: 2,
          }}
        >
          {/* Brand */}
          <Box display="flex" alignItems="center" gap={1.5}>
            <Scale size={22} color="#6366f1" />
            <Box>
              <Typography variant="subtitle2" fontWeight={800} color="text.primary">
                My Legal Notice India
              </Typography>
              <Typography variant="caption" color="text.secondary">
                © {new Date().getFullYear()} · AI-Powered Legal Drafting
              </Typography>
            </Box>
          </Box>

          {/* Links */}
          <Box display="flex" gap={3} flexWrap="wrap">
            {[
              { label: 'Privacy Policy', href: '/privacy' },
              { label: 'Terms of Service', href: '/terms' },
              { label: 'Contact', href: 'mailto:support@mylegalnotice.in' },
            ].map(link => (
              <Link key={link.label} href={link.href} style={{ textDecoration: 'none' }}>
                <Typography
                  variant="caption"
                  color="text.secondary"
                  sx={{
                    fontWeight: 500,
                    '&:hover': { color: 'primary.main' },
                    transition: 'color 0.15s'
                  }}
                >
                  {link.label}
                </Typography>
              </Link>
            ))}
          </Box>
        </Box>

        <Box mt={2} textAlign="center">
          <Typography variant="caption" color="text.secondary" sx={{ opacity: 0.6 }}>
            Governed by Indian law · Jurisdiction: India · Compliant with IT Act 2000 & DPDP Act 2023
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
