'use client';

import { Container, Typography, Box, Paper, Divider, Chip } from '@mui/material';
import Link from 'next/link';
import { FileText, AlertTriangle } from 'lucide-react';

export default function TermsOfServicePage() {
  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: [
        'By accessing or using My Legal Notice India ("the Service"), you agree to be bound by these Terms of Service.',
        'If you do not agree to these terms, please do not use the Service.',
        'These terms constitute a legally binding agreement between you and My Legal Notice India.'
      ]
    },
    {
      title: '2. Description of Service',
      content: [
        'My Legal Notice provides an AI-powered platform to help individuals and advocates draft legal notices, WhatsApp demand messages, and consumer court complaint templates.',
        'The Service uses artificial intelligence (Google Gemini and OpenRouter models) to generate document drafts based on information you provide.',
        'Documents are generated for informational and drafting assistance purposes only.'
      ]
    },
    {
      title: '3. ⚠️ IMPORTANT — Not Legal Advice',
      content: [
        'THE DOCUMENTS GENERATED BY THIS SERVICE ARE AI-DRAFTED TEMPLATES AND DO NOT CONSTITUTE LEGAL ADVICE.',
        'My Legal Notice is a technology tool, not a law firm, and is not engaged in the practice of law.',
        'Generated notices may contain errors, outdated law references, or may not be appropriate for your specific situation.',
        'You should consult a qualified and licensed advocate before sending any legal notice or filing any complaint.',
        'My Legal Notice is not responsible for any action taken based on documents generated by this service.',
        'The Advocates Act, 1961 regulates the practice of law in India. Nothing in this service should be construed as the practice of law.'
      ],
      highlight: true
    },
    {
      title: '4. User Responsibilities',
      content: [
        'You must provide accurate and truthful information when generating notices.',
        'You are solely responsible for verifying the accuracy of all information in generated documents before sending them.',
        'You must not use this Service to generate false, defamatory, harassing, or fraudulent legal notices.',
        'You must not use generated documents to threaten, intimidate, or harass any individual.',
        'Sending false or fabricated legal notices may constitute an offence under the Bharatiya Nyaya Sanhita 2023 and other Indian laws.',
        'You must be 18 years or older to use this Service.',
        'You are responsible for maintaining the confidentiality of your account credentials.'
      ]
    },
    {
      title: '5. Prohibited Uses',
      content: [
        'Generating notices based on false or fabricated facts.',
        'Using the Service to harass or intimidate individuals.',
        'Attempting to reverse-engineer, scrape, or copy the AI models or prompts.',
        'Reselling or commercializing generated documents without our written permission.',
        'Impersonating advocates or legal professionals when using the Lawyer mode without being a licensed advocate.',
        'Using automated bots or scripts to generate content in bulk.'
      ]
    },
    {
      title: '6. Intellectual Property',
      content: [
        'The documents you generate are yours. We do not claim ownership over your generated content.',
        'The Service itself, including its AI prompting logic, UI design, brand, and underlying code, is the intellectual property of My Legal Notice India.',
        'You may not reproduce or redistribute our platform or its core functionality without written permission.'
      ]
    },
    {
      title: '7. Limitation of Liability',
      content: [
        'My Legal Notice provides the Service "AS IS" without warranty of any kind.',
        'We are not liable for any direct, indirect, incidental, or consequential damages arising from use of the Service.',
        'We are not liable for the outcome of any legal proceeding resulting from documents generated by the Service.',
        'Our total liability in any case is limited to the amount paid by you for the Service in the preceding 3 months.',
        'We do not guarantee that generated documents will be accepted by any court, authority, or recipient.'
      ]
    },
    {
      title: '8. Accuracy of AI-Generated Content',
      content: [
        'AI-generated legal sections, BNS 2023 references, and court procedures may contain errors.',
        'Law section numbers, penalties, and legal standards cited by the AI should be independently verified.',
        'My Legal Notice does not guarantee the legal accuracy, currency, or completeness of generated notices.'
      ]
    },
    {
      title: '9. Termination',
      content: [
        'We reserve the right to suspend or terminate your account for violation of these Terms.',
        'You may close your account at any time by contacting us at support@mylegalnotice.in.'
      ]
    },
    {
      title: '10. Governing Law',
      content: [
        'These Terms are governed by the laws of India.',
        'Any disputes arising from the use of this Service shall be subject to the exclusive jurisdiction of the courts in India.',
        'These Terms are subject to the Information Technology Act, 2000 and rules made thereunder.'
      ]
    },
    {
      title: '11. Changes to Terms',
      content: [
        'We may update these Terms from time to time.',
        'Continued use of the Service after changes constitutes acceptance of the updated Terms.',
        'We will notify users of material changes via email or a prominent notice on the Service.'
      ]
    },
    {
      title: '12. Contact',
      content: [
        'For questions about these Terms: legal@mylegalnotice.in',
        'For support: support@mylegalnotice.in',
        'For privacy concerns: privacy@mylegalnotice.in'
      ]
    }
  ];

  return (
    <Box sx={{ minHeight: '100vh', py: 8, px: 2, bgcolor: 'background.default' }}>
      <Container maxWidth="md">
        <Box textAlign="center" mb={6}>
          <Box display="flex" justifyContent="center" mb={2}>
            <Box p={2} borderRadius="50%" bgcolor="rgba(99,102,241,0.1)">
              <FileText size={40} color="#6366f1" />
            </Box>
          </Box>
          <Typography variant="h3" fontWeight={800} mb={1}>Terms of Service</Typography>
          <Typography variant="body1" color="text.secondary">Last updated: 19 March 2026</Typography>
        </Box>

        <Paper
          elevation={0}
          sx={{
            p: { xs: 3, md: 5 },
            borderRadius: 4,
            border: '1px solid',
            borderColor: 'divider',
            mb: 4
          }}
        >
          {sections.map((section, i) => (
            <Box key={i} mb={4}>
              <Box display="flex" alignItems="center" gap={1} mb={2}>
                <Typography variant="h6" fontWeight={700} color={section.highlight ? 'error' : 'primary'}>
                  {section.title}
                </Typography>
                {section.highlight && (
                  <Chip
                    icon={<AlertTriangle size={14} />}
                    label="Must Read"
                    color="error"
                    size="small"
                    sx={{ fontWeight: 700, fontSize: '0.7rem' }}
                  />
                )}
              </Box>
              <Box
                sx={{
                  ...(section.highlight && {
                    p: 2.5,
                    bgcolor: 'rgba(239,68,68,0.04)',
                    borderLeft: '3px solid',
                    borderColor: 'error.main',
                    borderRadius: 1
                  })
                }}
              >
                <Box component="ul" sx={{ pl: 3, m: 0 }}>
                  {section.content.map((item, j) => (
                    <Typography
                      key={j}
                      component="li"
                      variant="body2"
                      color={section.highlight ? 'error.dark' : 'text.secondary'}
                      sx={{
                        mb: 1,
                        lineHeight: 1.8,
                        fontWeight: section.highlight ? 500 : 400
                      }}
                    >
                      {item}
                    </Typography>
                  ))}
                </Box>
              </Box>
              {i < sections.length - 1 && <Divider sx={{ mt: 3 }} />}
            </Box>
          ))}
        </Paper>

        <Box textAlign="center" pb={4}>
          <Typography variant="body2" color="text.secondary">
            By using My Legal Notice, you agree to these Terms.{' '}
            <Link href="/privacy" style={{ color: '#6366f1', textDecoration: 'none', fontWeight: 600 }}>
              View Privacy Policy →
            </Link>
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
