import { Box, Container, Typography } from '@mui/material';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use',
};

export default function TermsOfUsePage() {
  return (
    <Container maxWidth="md" sx={{ py: { xs: 8, md: 10 } }}>
      <Typography variant="h3" fontWeight={800} mb={4}>
        Terms of Use
      </Typography>

      <Box sx={{ typography: 'body1', color: 'text.secondary', lineHeight: 1.8, '& p': { mb: 3 } }}>
        <Typography paragraph><strong>Last Updated: March 2026</strong></Typography>

        <Typography paragraph>
          Welcome to My Legal Notice. By accessing and utilizing our AI Legal Notice Generator, you agree explicitly to these terms.
        </Typography>

        <Typography variant="h5" fontWeight={700} color="text.primary" mt={5} mb={2}>
          1. AI-Generated Drafts Are Not Legal Advice
        </Typography>
        <Typography paragraph>
          This platform utilizes generative AI to create basic drafting templates based on the user's inputs. <strong>We are not a law firm.</strong> Nothing generated by this application constitutes legal capability, legal advice, or attorney-client privilege.
        </Typography>

        <Typography variant="h5" fontWeight={700} color="text.primary" mt={5} mb={2}>
          2. Required Advocate Review
        </Typography>
        <Typography paragraph>
          The generated documents are <strong>drafts only</strong>. The underlying Bharatiya Nyaya Sanhita (BNS) 2023 laws and sections utilized by the AI might be incorrect, outdated, or misapplied to your specific facts. 
          You explicitly agree that you must have the final draft reviewed, corrected, and approved by an Enrolled Indian Advocate before finalizing or sending it. Sending any legal document without legal review may permanently weaken your position.
        </Typography>

        <Typography variant="h5" fontWeight={700} color="text.primary" mt={5} mb={2}>
          3. Absolute Liability Waiver (No Warranties)
        </Typography>
        <Typography paragraph>
          All services and documents provided via our application are offered "As-Is" and "As-Available" without any warranty of any kind, explicit or implied. 
          We do not verify your facts, the generated evidence, or the applicability to your case. 
          Under no circumstances shall the developers, founders, or affiliates of My Legal Notice be held liable for any damages, consequences, or legal counter-claims emerging from your utilization of this draft.
        </Typography>

        <Typography variant="h5" fontWeight={700} color="text.primary" mt={5} mb={2}>
          4. User Responsibility
        </Typography>
        <Typography paragraph>
          You are entirely and independently responsible for the factual accuracy representations injected into the AI-generated notice. You must not use our tool for harassment, fraudulent extortion, or maliciously frivolous litigation.
        </Typography>

        <Typography variant="h5" fontWeight={700} color="text.primary" mt={5} mb={2}>
          5. Governing Law and Jurisdiction
        </Typography>
        <Typography paragraph>
          The Terms and the usage of this site are governed by the laws of India. Any and all disputes arising in connection with the usage of this service shall be exclusively subject to the jurisdiction of the courts in Delhi, India.
        </Typography>
      </Box>
    </Container>
  );
}
